In [3]:
import numpy as np
x_test = np.array([[1, 2, 5], [3, 4, 8]], dtype=np.float64)
x_train = np.array([[4, 5, 7], [2, 3, 9], [2, 8, 1], [1, 5, 8], [4, 5, 3]], dtype=np.float64)

In [4]:
x_test

array([[1., 2., 5.],
       [3., 4., 8.]])

In [5]:
x_train

array([[4., 5., 7.],
       [2., 3., 9.],
       [2., 8., 1.],
       [1., 5., 8.],
       [4., 5., 3.]])

In [6]:
num_test = x_test.shape[0]
num_train = x_train.shape[0]
dists = np.zeros((num_test, num_train)) 
wrong_dists = np.zeros((num_test, num_train)) 
broadcast_dists = np.zeros((num_test, num_train)) 

### Trying to replicate this using broadcasting ...

In [7]:
for i in range(x_test.shape[0]):
    for j in range(x_train.shape[0]):
        dists[i][j] = np.sqrt(np.sum(np.square(x_train[j] - x_test[i])))

In [8]:
dists

array([[4.69041576, 4.24264069, 7.28010989, 4.24264069, 4.69041576],
       [1.73205081, 1.73205081, 8.1240384 , 2.23606798, 5.19615242]])

### Broacasting ...

In [9]:
for i in range(x_test.shape[0]):
    wrong_dists[i,:] = np.sqrt(np.sum(np.square(x_train - x_test[i]))) # Attempt1
    broadcast_dists[i,:] = np.sqrt(np.sum(np.square(x_train - x_test[i]), axis=1)) # Attempt2

In [10]:
print('wrong matrix...')
print(wrong_dists)
print('broadcast done right...')
print(broadcast_dists)

wrong matrix...
[[11.53256259 11.53256259 11.53256259 11.53256259 11.53256259]
 [10.19803903 10.19803903 10.19803903 10.19803903 10.19803903]]
broadcast done right...
[[4.69041576 4.24264069 7.28010989 4.24264069 4.69041576]
 [1.73205081 1.73205081 8.1240384  2.23606798 5.19615242]]


In [17]:
np.sum(x_train ** 2, axis=1, keepdims = True)

array([[90.],
       [94.],
       [69.],
       [90.],
       [50.]])

In [18]:
np.sum(x_train ** 2, axis=1)

array([90., 94., 69., 90., 50.])

In [19]:
np.sum(x_train ** 2)

393.0